/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package Analizador1;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 5;
  /** RegularExpression Id. */
  int DECIMAL = 6;
  /** RegularExpression Id. */
  int PARENI = 7;
  /** RegularExpression Id. */
  int PAREND = 8;
  /** RegularExpression Id. */
  int SUMA = 9;
  /** RegularExpression Id. */
  int RESTA = 10;
  /** RegularExpression Id. */
  int MULTIPLICACION = 11;
  /** RegularExpression Id. */
  int DIVISION = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUMERO>",
    "<DECIMAL>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
