/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package Analizador3.Generado;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARENI = 5;
  /** RegularExpression Id. */
  int PARENF = 6;
  /** RegularExpression Id. */
  int CBRACKETI = 7;
  /** RegularExpression Id. */
  int CBRACKETF = 8;
  /** RegularExpression Id. */
  int BRACKETI = 9;
  /** RegularExpression Id. */
  int BRACKETF = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
