/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package Analizador1.Generado;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int DECIMAL = 6;
  /** RegularExpression Id. */
  int PARENI = 7;
  /** RegularExpression Id. */
  int PARENF = 8;
  /** RegularExpression Id. */
  int ADDITION = 9;
  /** RegularExpression Id. */
  int SUBSTRACTION = 10;
  /** RegularExpression Id. */
  int PRODUCT = 11;
  /** RegularExpression Id. */
  int DIVISION = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUMBER>",
    "<DECIMAL>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
